In [2]:
#Se importan las librerias que se van a utilizar
import pandas as pd
import numpy as np
import glob
import os

In [15]:
## Se invoca el documento de excel 
df=pd.read_excel('../data/Coordenadas_localidades.xlsx') 


#Se imprimen los datos del DataFrame para validar que se hayan cargado correctamente

df

,LOCALIDAD,LONGITUD,LATITUD,CODIGO,gp
0,BARRIOS UNIDOS,-74.084000,4.666400,12,"-74.084, 4.6664"
1,ENGATIVÁ,-74.107200,4.707100,10,"-74.1072, 4.7071000000000005"
2,SUMAPAZ,-74.315224,4.034746,20,"-74.315224, 4.034746"
3,TEUSAQUILLO,-74.093800,4.644800,13,"-74.0938, 4.6448"
4,LA CANDELARIA,-74.073900,4.593900,17,"-74.0739, 4.5939"
5,SANTA FE,-74.029800,4.596300,3,"-74.0298, 4.5963"
6,SUBA,-74.082400,4.765200,11,"-74.0824, 4.7652"
7,FONTIBÓN,-74.147900,4.683200,9,"-74.1479, 4.6832"
8,LOS MÁRTIRES,-74.091300,4.603000,14,"-74.0913, 4.603"
9,SAN CRISTOBAL,-74.088300,4.546300,4,"-74.0883, 4.5463000000000005"
10,USME,-74.103300,4.476600,5,"-74.1033, 4.4766"
11,PUENTE ARANDA,-74.122700,4.614900,16,"-74.1227, 4.6149000000000004"
12,USAQUÉN,-74.031200,4.748500,1,"-74.0312, 4.7485"
13,BOGOTÁ,-74.081750,4.609710,0,"-74.08175, 4.60971"
14,BOSA,-74.194500,4.630500,7,"-74.1945, 4.6305"
15,CIUDAD BOLÍVAR,-74.153900,4.506600,19,"-74.1539, 4.5066"
16,RAFAEL URIBE URIBE,-74.116400,4.565300,18,"-74.1164, 4.5653"
17,KENNEDY,-74.157300,4.626800,8,"-74.1573, 4.6268"
18,CHAPINERO,-74.046700,4.656900,2,"-74.0467, 4.6569"
19,TUNJUELITO,-74.140700,4.587500,6,"-74.1407, 4.5875"
20,ANTONIO NARIÑO,-74.100900,4.548600,15,"-74.1009, 4.5486"

In [16]:
#Se renombran las columnas Nombre gp y CODIGO
df.rename(columns={'gp':'COORDENADAS','CODIGO': 'CODIGO_LOCALIDAD'},inplace=True)

In [17]:

#Se reorganiza el orden de las columnas
df = pd.DataFrame.reindex(df,columns =['CODIGO_LOCALIDAD','LOCALIDAD','LONGITUD','LATITUD','COORDENADAS'])

In [18]:
#Se imprimen los datos del DataFrame para validar que se hayan aplicado correctamente los cambios
df

,CODIGO_LOCALIDAD,LOCALIDAD,LONGITUD,LATITUD,COORDENADAS
0,12,BARRIOS UNIDOS,-74.084000,4.666400,"-74.084, 4.6664"
1,10,ENGATIVÁ,-74.107200,4.707100,"-74.1072, 4.7071000000000005"
2,20,SUMAPAZ,-74.315224,4.034746,"-74.315224, 4.034746"
3,13,TEUSAQUILLO,-74.093800,4.644800,"-74.0938, 4.6448"
4,17,LA CANDELARIA,-74.073900,4.593900,"-74.0739, 4.5939"
5,3,SANTA FE,-74.029800,4.596300,"-74.0298, 4.5963"
6,11,SUBA,-74.082400,4.765200,"-74.0824, 4.7652"
7,9,FONTIBÓN,-74.147900,4.683200,"-74.1479, 4.6832"
8,14,LOS MÁRTIRES,-74.091300,4.603000,"-74.0913, 4.603"
9,4,SAN CRISTOBAL,-74.088300,4.546300,"-74.0883, 4.5463000000000005"
10,5,USME,-74.103300,4.476600,"-74.1033, 4.4766"
11,16,PUENTE ARANDA,-74.122700,4.614900,"-74.1227, 4.6149000000000004"
12,1,USAQUÉN,-74.031200,4.748500,"-74.0312, 4.7485"
13,0,BOGOTÁ,-74.081750,4.609710,"-74.08175, 4.60971"
14,7,BOSA,-74.194500,4.630500,"-74.1945, 4.6305"
15,19,CIUDAD BOLÍVAR,-74.153900,4.506600,"-74.1539, 4.5066"
16,18,RAFAEL URIBE URIBE,-74.116400,4.565300,"-74.1164, 4.5653"
17,8,KENNEDY,-74.157300,4.626800,"-74.1573, 4.6268"
18,2,CHAPINERO,-74.046700,4.656900,"-74.0467, 4.6569"
19,6,TUNJUELITO,-74.140700,4.587500,"-74.1407, 4.5875"
20,15,ANTONIO NARIÑO,-74.100900,4.548600,"-74.1009, 4.5486"

In [19]:
#Se exporta el DataFrame en un archivo tipo xlsx con el formato utf-8
df.to_excel('Coordenadas_localidades_Bogota.xlsx',encoding="utf-8", index=False)