
Limpieza de datos - Datos de los delitos de alto impacto

In [1]:
#Se importan las librerias que se van a utilizar
import pandas as pd
import numpy as np
import glob
import os

In [2]:
#CARGA DE DATOS


#Se fusionan los archivos que estan separados por año desde el 2018 hasta el 2019

archivos_unidos = os.path.join("../data","DATOS*.xlsx")

#Se devuelve una lista de todos los archivos unidos

Lista_archivos = glob.glob(archivos_unidos)

#los archivos se unen

datos = pd.concat(map(pd.read_excel, Lista_archivos), ignore_index= True)

In [50]:

#Se almacenan los datos en un DataFrame

df= pd.DataFrame(datos, columns = ['Fecha','Año','Nro del Mes','Mes','Localidad','UPZ','Delito','Sexo','Nombre Dia','Rango del Dia','Arma Empleada','Numero Hechos'])

#Se imprimen los datos del DataFrame para validar que se hayan cargado correctamente

df

,Fecha,Año,Nro del Mes,Mes,Localidad,UPZ,Delito,Sexo,Nombre Dia,Rango del Dia,Arma Empleada,Numero Hechos
0,2018-04-30,2018,4,ABR,15 - ANTONIO NARIÑO,RESTREPO,HURTO DE CELULARES,-,LUNES,TARDE,ARMA DE FUEGO,20
1,2018-04-29,2018,4,ABR,15 - ANTONIO NARIÑO,RESTREPO,HURTO DE CELULARES,-,DOMINGO,MADRUGADA,SIN EMPLEO DE ARMAS,12
2,2018-02-13,2018,2,FEB,15 - ANTONIO NARIÑO,RESTREPO,HURTO DE BICICLETAS,-,MARTES,MAÑANA,SIN EMPLEO DE ARMAS,10
3,2018-12-05,2018,12,DIC,15 - ANTONIO NARIÑO,RESTREPO,HURTO DE CELULARES,-,MIÉRCOLES,MADRUGADA,SIN EMPLEO DE ARMAS,8
4,2018-08-08,2018,8,AGO,15 - ANTONIO NARIÑO,CIUDAD JARDIN,LESIONES EN AT,FEMENINO,MIÉRCOLES,NOCHE,VEHICULO,7
...,...,...,...,...,...,...,...,...,...,...,...,...
1370108,2022-08-09,2022,8,AGO,99 - SIN LOCALIZACION,SIN LOCALIZACION,HURTO A PERSONAS,MASCULINO,MARTES,TARDE,NO REPORTADO,1
1370109,2022-08-09,2022,8,AGO,99 - SIN LOCALIZACION,SIN LOCALIZACION,HURTO DE CELULARES,MASCULINO,MARTES,TARDE,NO REPORTADO,1
1370110,2022-08-09,2022,8,AGO,99 - SIN LOCALIZACION,SIN LOCALIZACION,HURTO DE CELULARES (CASOS),MASCULINO,MARTES,TARDE,NO REPORTADO,1
1370111,2022-08-10,2022,8,AGO,99 - SIN LOCALIZACION,SIN LOCALIZACION,LESIONES EN AT,FEMENINO,MIÉRCOLES,TARDE,SIN EMPLEO DE ARMAS,1
1370112,2022-08-23,2022,8,AGO,99 - SIN LOCALIZACION,SIN LOCALIZACION,LESIONES EN AT,MASCULINO,MARTES,TARDE,SIN EMPLEO DE ARMAS,1

In [51]:
#COLUMNA LOCALIDAD:

#Se eliminan los datos de la columna localidad que aparezcan sin localizacion 
df = df.drop(df[df['Localidad']=='99 - SIN LOCALIZACION'].index)

#Se modifican los datos de la columna localidad para dejar solo el nombre de la localidad sin el codigo
df.loc[df['Localidad'] == '01 - USAQUÉN', 'Localidad'] = 'USAQUÉN'
df.loc[df['Localidad'] == '02 - CHAPINERO', 'Localidad'] = 'CHAPINERO'
df.loc[df['Localidad'] == '03 - SANTA FE', 'Localidad'] = 'SANTA FE'
df.loc[df['Localidad'] == '04 - SAN CRISTÓBAL', 'Localidad'] = 'SAN CRISTÓBAL'
df.loc[df['Localidad'] == '05 - USME', 'Localidad'] = 'USME'
df.loc[df['Localidad'] == '06 - TUNJUELITO', 'Localidad'] = 'TUNJUELITO'
df.loc[df['Localidad'] == '07 - BOSA', 'Localidad'] = 'BOSA'
df.loc[df['Localidad'] == '08 - KENNEDY', 'Localidad'] = ' KENNEDY'
df.loc[df['Localidad'] == '09 - FONTIBÓN', 'Localidad'] = 'FONTIBÓN'
df.loc[df['Localidad'] == '10 - ENGATIVÁ', 'Localidad'] = 'ENGATIVÁ'
df.loc[df['Localidad'] == '11 - SUBA', 'Localidad'] = 'SUBA'
df.loc[df['Localidad'] == '12 - BARRIOS UNIDOS', 'Localidad'] = 'BARRIOS UNIDOS'
df.loc[df['Localidad'] == '13 - TEUSAQUILLO', 'Localidad'] = ' TEUSAQUILLO'
df.loc[df['Localidad'] == '14 - LOS MÁRTIRES', 'Localidad'] = 'LOS MÁRTIRES'
df.loc[df['Localidad'] == '15 - ANTONIO NARIÑO', 'Localidad'] = 'ANTONIO NARIÑO'
df.loc[df['Localidad'] == '16 - PUENTE ARANDA', 'Localidad'] = ' PUENTE ARANDA'
df.loc[df['Localidad'] == '17 - CANDELARIA', 'Localidad'] = 'CANDELARIA'
df.loc[df['Localidad'] == '18 - RAFAEL URIBE URIBE', 'Localidad'] = 'RAFAEL URIBE URIBE'
df.loc[df['Localidad'] == '19 - CIUDAD BOLÍVAR', 'Localidad'] = 'CIUDAD BOLÍVAR'
df.loc[df['Localidad'] == '20 - SUMAPAZ', 'Localidad'] = 'SUMAPAZ'

In [52]:
#COLUMNA DELITOS:

#Se eliminan los datos de la columna delito que pertenezcan a accidentes de transito (AT)
df = df.drop(df[df['Delito']=='HOMICIDIOS EN AT'].index)
df = df.drop(df[df['Delito']=='LESIONES EN AT'].index)

#Se eliminan los datos de la columna delito que pertenezcan a VIOLENCIA INTRAFAMILIAR
df = df.drop(df[df['Delito']=='VIOLENCIA INTRAFAMILIAR'].index)

#Se unifica en la columna delito los datos que los hurtos de celulares
df.loc[df['Delito'] == 'HURTO DE CELULARES (CASOS)', 'Delito'] = 'HURTO DE CELULARES'

#Se eliminan los datos de la columna delito que pertenezcan a DELITOS SEXUALES
df = df.drop(df[df['Delito']=='DELITOS SEXUALES'].index)

#Se eliminan los datos de la columna delito que pertenezcan a AMENAZAS
df = df.drop(df[df['Delito']=='AMENAZAS'].index)

#Se eliminan los datos de la columna delito que pertenezcan a HURTO PIRATERIA TERRESTRE
df = df.drop(df[df['Delito']=='HURTO PIRATERIA TERRESTRE'].index)

#Se eliminan los datos de la columna delito que pertenezcan a HURTO ABIGEATO
df = df.drop(df[df['Delito']=='HURTO ABIGEATO'].index)

#Se eliminan los datos de la columna delito que pertenezcan a EXTORSION
df = df.drop(df[df['Delito']=='EXTORSION'].index)

#Se eliminan los datos de la columna delito que pertenezcan a SECUESTRO

df = df.drop(df[df['Delito']=='SECUESTRO'].index)
#Se eliminan los datos de la columna delito que pertenezcan a TERRORISMO
df = df.drop(df[df['Delito']=='TERRORISMO'].index)

In [53]:
#COLUMNA UPZ:

#Se eliminan los datos de la columna localidad que aparezcan sin localizacion 
df = df.drop(df[df['UPZ']=='SIN LOCALIZACION'].index)

In [54]:
#COLUMNA SEXO:

#En la columna sexo se cambian los datos que aparezcan asi '-' por el sexo 'INDEFINIDO'
df.loc[df['Sexo'] == '-', 'Sexo'] = 'INDEFINIDO'

#ARMA EMPLEADA:

#En la columna Arma Empleada se cambian los datos que aparezcan asi '-' por 'SIN INFORMACION'
df.loc[df['Arma Empleada'] == '-', 'Arma Empleada'] = 'SIN EMPLEO DE ARMAS'

In [55]:
#COLUMNA FECHA:

#Se modifica el tipo de dato de la columna FECHA 

df['Fecha'] = df['Fecha'].astype(str)

In [56]:
#COLUMNA MES:

#Se modifican los datos de la columna Mes para dejar dejar el nombre completo de los meses
df.loc[df['Mes'] == 'ENE', 'Mes'] = 'ENERO'
df.loc[df['Mes'] == 'FEB', 'Mes'] = 'FEBRERO'
df.loc[df['Mes'] == 'MAR', 'Mes'] = 'MARZO'
df.loc[df['Mes'] == 'ABR', 'Mes'] = 'ABRIL'
df.loc[df['Mes'] == 'MAY', 'Mes'] = 'MAYO'
df.loc[df['Mes'] == 'JUN', 'Mes'] = 'JUNIO'
df.loc[df['Mes'] == 'JUL', 'Mes'] = 'JULIO'
df.loc[df['Mes'] == 'AGO', 'Mes'] = 'AGOSTO'
df.loc[df['Mes'] == 'SEP', 'Mes'] = 'SEPTIEMBRE'
df.loc[df['Mes'] == 'OCT', 'Mes'] = 'OCTUBRE'
df.loc[df['Mes'] == 'NOV', 'Mes'] = 'NOVIEMBRE'
df.loc[df['Mes'] == 'DIC', 'Mes'] = 'DICIEMBRE'

In [57]:
#COLUMNAS 

#Se crea una nueva columna con el numero de la localidad
conditionlist = [
(df['Localidad'] == 'USAQUÉN'),
(df['Localidad'] == 'CHAPINERO'),
(df['Localidad'] == 'SANTA FE'),
(df['Localidad'] == 'SAN CRISTÓBAL'),
(df['Localidad'] == 'USME'),
(df['Localidad'] == 'TUNJUELITO'),
(df['Localidad'] == 'BOSA'),
(df['Localidad'] == 'KENNEDY'),
(df['Localidad'] == 'FONTIBÓN' ),
(df['Localidad'] == 'ENGATIVÁ'),
(df['Localidad'] == 'SUBA'),
(df['Localidad'] == 'BARRIOS UNIDOS'),
(df['Localidad'] == 'TEUSAQUILLO'),
(df['Localidad'] == 'LOS MÁRTIRES' ),
(df['Localidad'] == 'ANTONIO NARIÑO'),
(df['Localidad'] == 'PUENTE ARANDA'),
(df['Localidad'] == 'CANDELARIA'),
(df['Localidad'] == 'RAFAEL URIBE URIBE'),
(df['Localidad'] == 'CIUDAD BOLÍVAR'),
(df['Localidad'] == 'SUMAPAZ')]
choicelist =   ['1',
                '2',
                '3',
                '4',
                '5',
                '6',
                '7',
                '8',
                '9',
                '10',
                '11',
                '12',
                '13',
                '14',
                '15',
                '16',
                '17',
                '18',
                '19',
                '20']
df['Codigo_localidad'] = np.select(conditionlist, choicelist, default='Not Specified')

#Se crea una nueva columna con el articulo correspondiente a los delitos
conditionlist = [
    (df['Delito'] == 'HURTO A PERSONAS'),
    (df['Delito'] == 'LESIONES PERSONALES'),
    (df['Delito'] == 'HURTO A ENTIDADES COMERCIALES'),
    (df['Delito'] == 'HOMICIDIOS'),
    (df['Delito'] == 'HURTO AUTOMOTORES'),
    (df['Delito'] == 'HURTO A RESIDENCIAS'),
    (df['Delito'] == 'HURTO A ENTIDADES FINANCIERAS'),
    (df['Delito'] == 'HURTO MOTOCICLETAS'),
    (df['Delito'] == 'HURTO A COMERCIO'),
    (df['Delito'] == 'HURTO DE BIENES PATRIMONIO CULTURAL DE LA NACIÓN')]
choicelist = ['239_HP', 
              '111_LP',
              '239_HEC',
              '103_HO',
              '239_HA',
              '239_HR',
              '239_HEF',
              '239_HM',
              '239_HCO',
              '239_HB']

df['Articulo'] = np.select(conditionlist, choicelist, default='239_HP')


#Se reorganiza el orden de las columnas

df = pd.DataFrame.reindex(df,columns =['Fecha','Año','Nro del Mes','Mes','Codigo_localidad','Localidad','UPZ','Articulo','Delito','Sexo','Nombre Dia','Rango del Dia','Arma Empleada','Numero Hechos'])



#Se renombran las columnas Nombre Dia,Rango del Dia,Arma Empleada,Numero Hechos y Nro del Mes

df.rename(columns={'Nombre Dia':'Dia','Rango del Dia': 'Rango_Dia', 'Arma Empleada':'Arma','Numero Hechos':'Numero_Hechos','Nro del Mes': 'Numero_Mes'},inplace=True)


#Todas las columnas quedan en mayuscula

df.columns = map(lambda x: str(x).upper(), df.columns)

In [58]:
#Se imprimen los datos del DataFrame para validar que se hayan aplicado correctamente los cambios
df

,FECHA,AÑO,MES,CODIGO_LOCALIDAD,LOCALIDAD,UPZ,ARTICULO,DELITO,SEXO,DIA,RANGO_DIA,ARMA,NUMERO_HECHOS
0,2018-04-30,2018,ABRIL,15,ANTONIO NARIÑO,RESTREPO,239_HP,HURTO DE CELULARES,INDEFINIDO,LUNES,TARDE,ARMA DE FUEGO,20
1,2018-04-29,2018,ABRIL,15,ANTONIO NARIÑO,RESTREPO,239_HP,HURTO DE CELULARES,INDEFINIDO,DOMINGO,MADRUGADA,SIN EMPLEO DE ARMAS,12
2,2018-02-13,2018,FEBRERO,15,ANTONIO NARIÑO,RESTREPO,239_HP,HURTO DE BICICLETAS,INDEFINIDO,MARTES,MAÑANA,SIN EMPLEO DE ARMAS,10
3,2018-12-05,2018,DICIEMBRE,15,ANTONIO NARIÑO,RESTREPO,239_HP,HURTO DE CELULARES,INDEFINIDO,MIÉRCOLES,MADRUGADA,SIN EMPLEO DE ARMAS,8
5,2018-10-22,2018,OCTUBRE,15,ANTONIO NARIÑO,RESTREPO,239_HP,HURTO DE CELULARES,FEMENINO,LUNES,NOCHE,ARMA BLANCA / CORTOPUNZANTE,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1370073,2022-08-31,2022,AGOSTO,19,CIUDAD BOLÍVAR,SAN FRANCISCO,239_HP,HURTO A PERSONAS,MASCULINO,MIÉRCOLES,TARDE,ARMA BLANCA / CORTOPUNZANTE,1
1370074,2022-08-31,2022,AGOSTO,19,CIUDAD BOLÍVAR,SAN FRANCISCO,239_HR,HURTO A RESIDENCIAS,MASCULINO,MIÉRCOLES,MAÑANA,SIN EMPLEO DE ARMAS,1
1370096,2022-06-26,2022,JUNIO,20,SUMAPAZ,UPR RIO BLANCO,111_LP,LESIONES PERSONALES,FEMENINO,DOMINGO,MADRUGADA,SIN EMPLEO DE ARMAS,1
1370098,2022-07-18,2022,JULIO,20,SUMAPAZ,UPR RIO SUMAPAZ,111_LP,LESIONES PERSONALES,MASCULINO,LUNES,TARDE,SIN EMPLEO DE ARMAS,1
1370100,2022-08-21,2022,AGOSTO,20,SUMAPAZ,UPR RIO BLANCO,111_LP,LESIONES PERSONALES,MASCULINO,DOMINGO,MAÑANA,SIN EMPLEO DE ARMAS,1

In [59]:

#Se agrupan los datos en 3 DataFrames diferentes por el rango de tiempo (pre_pandemia,pandemia y post_pandemia )

pre_pandemia =  df.query("AÑO in (2018,2019)")
pandemia =  df.query("AÑO == 2020  or (AÑO == 2021 and (MES == 'ENERO' or MES == 'FEBRERO' or MES == 'MARZO' or MES == 'ABRIL' \
                      or MES == 'MAYO' or MES == 'JUNIO'))")

post_pandemia =  df.query("AÑO == 2022  or (AÑO == 2021 and (MES == 'JULIO' or MES == 'AGOSTO' or MES == 'SEPTIEMBRE' or MES == 'OCTUBRE' \
                      or MES == 'NOVIEMBRE' or MES == 'DICIEMBRE'))")

In [60]:
#Se exportan los 3 DataFrames en 3 arhivos tipo xlsx con el formato utf-8
pre_pandemia.to_excel('Delitos_prepandemia.xlsx',encoding="utf-8", index=False)
pandemia.to_excel('Delitos_pandemia.xlsx',encoding="utf-8", index=False)
post_pandemia.to_excel('Delitos_postpandemia.xlsx',encoding="utf-8", index=False)